name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.AUTODEPLOY_SCRAPER_SWATDIMONBIL }}
          
      - name: Create back-nest .env file
        run: |
          echo "${{ secrets.PRODUCTION_BACKNEST_ENV_FILE }}" > back-nest/.env

      - name: Create frontend .env file
        run: |
          echo "${{ secrets.PRODUCTION_FRONTEND_ENV_FILE }}" > frontend/.env

      - name: Set permissions
        run: |
          chmod 600 back-nest/.env
          chmod 600 frontend/.env

      - name: Run deploy script
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@3.74.165.43 'cd ./NestTestBandaPixels && git pull && docker compose up -d'
